// "/zh/form/": [
//     {
//         text: "关于",
//         items: [
//             { text: "安装", link: "/zh/form/intro/install" },
//             { text: "快速入门", link: "/zh/form/intro/get-started" },
//         ],
//     },
//     {
//         text: "指南",
//         items: [
//             { text: "表单", link: "/zh/form/guide/form" },
//             { text: "字段", link: "/zh/form/guide/field" },
//             { text: "校验", link: "/zh/form/guide/validate" },
//             { text: "提交表单", link: "/zh/form/guide/submit" },
//             { text: "图标", link: "/zh/form/guide/icons" },
//         ],
//     },
//     {
//         text: "字段",
//         items: [
//             { text: "Input", link: "/zh/form/guide/fields/input" },
//             { text: "Number", link: "/zh/form/guide/fields/number" },
//             { text: "Date", link: "/zh/form/guide/fields/date" },
//             { text: "Time", link: "/zh/form/guide/fields/time" },
//             { text: "DateTime", link: "/zh/form/guide/fields/datetime" },
//             { text: "Phone", link: "/zh/form/guide/fields/phone" },
//             { text: "Email", link: "/zh/form/guide/fields/email" },
//             { text: "DateRange", link: "/zh/form/guide/fields/date-range" },
//             { text: "Url", link: "/zh/form/guide/fields/url" },
//             { text: "Search", link: "/zh/form/guide/fields/search" },
//             { text: "Checkbox", link: "/zh/form/guide/fields/checkbox" },
//             { text: "CheckboxGroup", link: "/zh/form/guide/fields/checkbox-group" },
//             { text: "ColorPicker", link: "/zh/form/guide/fields/colorpicker" },
//             { text: "Cascader", link: "/zh/form/guide/fields/cascader" },
//             { text: "Switch", link: "/zh/form/guide/fields/switch" },
//             { text: "Radio", link: "/zh/form/guide/fields/radio" },
//             { text: "RadioButton", link: "/zh/form/guide/fields/radio-button" },
//             { text: "List", link: "/zh/form/guide/fields/list" },
//             { text: "Select", link: "/zh/form/guide/fields/select" },
//             { text: "TreeSelect", link: "/zh/form/guide/fields/tree-select" },
//             { text: "TreeDropdown", link: "/zh/form/guide/fields/tree-dropdown" },
//             { text: "Rating", link: "/zh/form/guide/fields/rating" },
//             { text: "Range", link: "/zh/form/guide/fields/range" },
//             { text: "Textarea", link: "/zh/form/guide/fields/textarea" },
//             { text: "Upload", link: "/zh/form/guide/fields/upload" },
//             { text: "Parts", link: "/zh/form/guide/fields/parts" },
//             { text: "Captcha", link: "/zh/form/guide/fields/captcha" },
//             { text: "VerifyCode", link: "/zh/form/guide/fields/verify-code" },
//             { text: "IpAddress", link: "/zh/form/guide/fields/ipaddress" },
//             { text: "Icons", link: "/zh/form/guide/fields/icons" },
//             { text: "Combine", link: "/zh/form/guide/fields/combine" },
//             { text: "Custom", link: "/zh/form/guide/fields/custom" },
//             { text: "QrCode", link: "/zh/form/guide/fields/qrcode" },
//         ],
//     },
//     {
//         text: "字段组",
//         items: [
//             { text: "Tabs", link: "/zh/form/guide/groups/tabs" },
//             { text: "Collapse", link: "/zh/form/guide/groups/collapse" },
//         ],
//     },
//     {
//         text: "示例",
//         items: [{ text: "综合", link: "/examples/demo.html", target: "_blank" }],
//     },
// ],
